Repository chinmay29hub/haiku-readme, pull requests merged in 2025-05, with the labels that each got.

#7 fix: fixed linting and format of backend/ and frontend/
  backend/eslint.config.mjs
  backend/index.js
  backend/lib/haiku.js
  backend/lib/svg.js
  backend/lib/templates.json
  backend/lib/words.json
  backend/package-lock.json
  frontend/index.html
  frontend/public/google7af5221bd040abb5.html
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/main.jsx
  frontend/vite.config.js
Labels: size/L

#10 Add: .editorconfig for consistent formatting
  .editorconfig
Labels: size/XS

#12 added command to restrict deployment from main branch
  vercel.json
Labels: size/S

#26 Remove: Remove test.md file from root directory
  test.md
Labels: size/XS

#27 Added a randomize button that will select random appearances from dro…
  frontend/src/App.jsx
Labels: size/S

#28 adding logger middleware
  backend/index.js
  backend/middleware/logging/logging.middleware.js
Labels: size/S

#11 added 2 new themes
  backend/lib/svg.js
  frontend/src/App.jsx
Labels: size/S
